spring:
  application:
    name: service-order
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
    nacos:
      server-addr: 127.0.0.1:8848

feign:
  sentinel:
    enabled: true

server:
  port: 8000

logging:
  level:
    com.showlee.order.feign: DEBUG